#%RAML 0.8
---
title: Sample API

schemas:
    - global: !include refs/fstab-referring.json

/resource:
    put:
        body:
            application/json:
                schema: !include refs/fstab-referring.json
                #schema: !include refs/fstab.json
        responses:
            200:
                body:
                    text/plain: ~
/global:
    put:
        #body: !include refs/xsd-global.raml
        body:
            application/json:
                schema: global

/global-include:
    put:
        body: !include refs/json-schema-global.raml
