#%RAML 0.8
title: Validation API
baseUri: http://localhost:8083/api

/jsonschema:
    put:
      body:
          application/json:
                schema: !include json-schema.json
      responses:
            200:
                body: