#%RAML 1.0
title: Sample API
version: v1

/resource/{version}:
  get:
    description: |
      Retrieve resource(s)
    responses:
      200:
        description: |
          Successfully retrieved resource(s)
