#%RAML 1.0
title: Petshop
version: 1.0

/customers:
  post:
    body:
      application/json:
        example: { "name" : "Lorena", "surname" : "Daicich" }
  /pets:
    get:
      responses:
        200:
          body:
            application/json:
              example: {"name" : "Mandy", "age" : 3 }