#%RAML 0.8
---
title: Simple API
baseUri: http://localhost:8081
/resources:
  get:
    responses:
        200:
            body:
                application/json: !!null
                text/xml: !!null
