#%RAML 1.0
version: 1.0
baseUri: http://training-american-ws.cloudhub.io/api/
title: American Flights API

types:
  AmericanFlight: !include exchange_modules/68ef9520-24e9-4cf2-b2f5-620025690913/training-american-flight-data-type/1.0.1/AmericanFlightDataType.raml

/flights:
  get:
    displayName: Get all flights
    queryParameters: 
      destination:
        displayName: Destination airport code  
        required: false
        enum: [SFO, LAX, CLE]
    responses: 
      200:
        body: 
          application/json:
            type: AmericanFlight[]
            examples: !include exchange_modules/68ef9520-24e9-4cf2-b2f5-620025690913/training-american-flights-example/1.0.1/AmericanFlightsExample.raml
  post:
    displayName: Add a flight
    body: 
      application/json:
        type: AmericanFlight
        examples: !include examples/AmericanFlightNoIDExample.raml
    responses: 
      201:
        body: 
          application/json:
            example:
              message: Flight added (but not really)
  /{ID}:
    uriParameters:
        ID:
          type: integer
          example: 10
          description: Represents the flight unique id
    get:
      displayName: Get a flight by ID
      responses: 
        200:
          body: 
            application/json:
              type: AmericanFlight
              examples: !include examples/AmericanFlightExample.raml
    delete:
      displayName: Delete a flight
      responses:
        200:
          body:
            application/json:
              example:
                message: Flight deleted (but not really)
    put:
      displayName: Update a flight
      body:
        application/json:
          type: AmericanFlight
          examples: !include examples/AmericanFlightExample.raml
      responses:
        200:
          body:
            application/json:
              example:
                message: Flight updated (but not really)
