#%RAML 1.0 DataType

properties:
  weight:
    description: in gramm
    type: integer
    minimum: 1
    example: 2000
  length:
    description: in mm
    type: integer
    minimum: 1
    example: 400
  width:
    description: in mm
    type: integer
    minimum: 1
    example: 200
  height:
    description: in mm
    type: integer
    minimum: 1
    example: 10