#%RAML 0.8
title: filter api
/some:
    put: &a
        body:
            text/plain: ~
        responses:
            200:
                body:
                    text/plain: ~
/throw:
    put: *a
