#%RAML 1.0
title: RAML 1.0 Xsd Project
version: v1
baseUri: https://www.example.com/api/

types:
  Item:
    schema: !include item.xsd

/resource/item:
  get:
    responses:
      200:
        body:
          application/xml:
            type: Item