#%RAML 1.0
---
title: Simple API
baseUri: http://localhost:8081

/resource:
  get:
    responses:
        200:
            body:
                application/json: !!null
                text/xml: !!null

/error:
  get:
    responses:
        200:
            body:
                application/json: !!null
                text/xml: !!null