headers: 
  GData-Version: 
    description: |
      Version of Google Contacts API
    example: 3.0
queryParameters: 
  v: 
    description: |
      Alternatively, if you can't set HTTP headers, you can specify v=3.0 as a query parameter in the URL.
      The HTTP header is preferred where possible.
    example: 3.0
