#%RAML 1.0
---
title: Simple API 2
baseUri: http://localhost:8081
types:
  Person:
    type: object
    properties:
      name:
        required: true
        type: string
/typesPerson:
  post:
    body:
        application/json:
            type: Person
    responses:
      200: ~
