#%RAML 0.8
---
title: Sample API
version: v1
baseUri: http://localhost/api
/pet:
    displayName: Pets
    get:
        responses:
            200:
                body:
                    application/json: !!null
                    text/xml: !!null
    post:
        responses:
            200:
                body:
                    application/json: !!null
                    text/xml: !!null
/car:
    displayName: Cars
    get:
        responses:
            200:
                body:
                    application/json: !!null
                    text/xml: !!null
    post:
        responses:
            200:
                body:
                    application/json: !!null
                    text/xml: !!null
