#%RAML 1.0
---
title: Sample API
version: v1
baseUri: http://localhost/api
/: &resource
    displayName: Leagues
    get:
        responses:
            200:
                body:
                    application/json: !!null
                    text/xml: !!null

/pet: *resource

/pet/{version}: *resource
