#%RAML 1.0
title: Test API
version: '1.0'
types:
  Person:
    type: object
    properties:
      idNumber:
        type: integer
      firstName:
        type: string
      lastName:
        type: string
        required: false
  Event:
    type: !include schema.json
/schemaJson:
  post:
    body:
      application/json:
        type: Event
/bodyJson:
  post:
    body:
      application/json:
        type: Person
/someJsonError:
  post:
    body:
      application/json: {}