#%RAML 0.8
---
title: Parameters API

/multipart:
  post:
    body:
      multipart/form-data:
        formParameters:
          first:
            type: string
            required: true
          second:
            type: string
            required: true
            default: segundo
          third:
            type: boolean
            default: true
          fourth:
            type: string
    responses:
      201: ~
/url-encoded-simple:
  post:
    body:
      application/x-www-form-urlencoded:
        formParameters:
          first:
            type: string
    responses:
      201: ~
/url-encoded-with-default:
  post:
    body:
      application/x-www-form-urlencoded:
        formParameters:
          first:
            type: string
            default: primo
          second:
            type: string
            required: true
          third:
            type: boolean
    responses:
      201: ~
/url-encoded-duplicated-key:
  post:
    body:
      application/x-www-form-urlencoded:
        formParameters:
          first:
            type: string
            default: primo
          second:
            type: string
            required: true
          third:
            type: boolean
    responses:
      201: ~
/uploadImage:
  post:
    body:
      multipart/form-data:
        formParameters:
          image:
            required: true
            type: file

/uploadFile:
  post:
    body:
      multipart/form-data:
        formParameters:
          document:
            required: true
            type: file
/users:
  post:
    body:
      multipart/form-data:
        formParameters:
          userId:
            required: true
            type: integer

/announcements:
  post:
    body:
      multipart/form-data:
        formParameters:
          content:
            required: false
            type: string
            maxLength: 10
/multiple-required-multipart:
  post:
    body:
      multipart/form-data:
        formParameters:
          userId:
            type: string
            required: true
          second:
            type: string
            required: true
          third:
            type: boolean
            required: true
    responses:
      201: ~
/multiple-optional-multipart:
  post:
    body:
      multipart/form-data:
        formParameters:
          first:
            type: string
            required: false
          second:
            type: string
            default: segundo
          third:
            type: boolean
            default: true
    responses:
      201: ~