#%RAML 0.8
---
title: Sample API
version: v1
baseUri: http://localhost/api
/:
    displayName: Root
    get:
        responses:
            200:
                body:
                    application/json: !!null
                    text/xml: !!null
/pet:
    displayName: Leagues
    get:
        responses:
            200:
                body:
                    application/json: !!null
                    text/xml: !!null
    post:
        responses:
            200:
                body:
                    application/json: !!null
                    text/xml: !!null
