#%RAML 0.8
---
title: Leagues API
version: v1
baseUri: http://localhost/originalapi

/user:
    displayName: User
    get:
        responses:
            200:
                body:
                    application/json:
                        example: '{"name":"jane"}'
