#%RAML 1.0
title: Test API
description: 'To test stuff'
version: 2.0.0
mediaType: application/json
protocols:
  - HTTP

uses:     
  myLib : exchange_modules/library-reference-to-root-with-apisync/raml-library/1.1.0/reused-fragment.raml

/test:
  get:
    description: uses dependency type
    responses:
      '200':
        description: a dependency type
        body:
          application/json:
            type: myLib.moreStuff
