#%RAML 0.8
title: sample api
/currentuser:
    put:
        body:
            application/json:
                schema: |
                    {
                       "type":"object",
                       "id":"urn:jsonschema:org:mule:module:apikit:schema:User",
                       "properties":{
                          "firstName":{
                             "type":"string",
                             "required":true
                          },
                          "lastName":{
                             "type":"string",
                             "required":true
                          },
                          "emailAddresses":{
                             "type":"array",
                             "required":true,
                             "items":{
                                "type":"string"
                             }
                          },
                          "username":{
                             "type":"string",
                             "required":true
                          }
                       }
                    }
            text/xml:
                schema: !jaxb org.mule.module.apikit.validation.body.schema.User
        responses:
            204: ~

