#%RAML 1.0

title: Parameters API

/repeat:
    get:
        queryParameters:
            status:
                type: string[]
                minItems: 1
                required: false
            union-string:
                type: nil | string
                required: false
        responses:
            200:
                body:
                    text/plain: ~

/repeatHeader:
    get:
        headers:
            repeatable:
                type: array
        responses:
            200:
                body:
                    text/plain: ~