#%RAML 1.0
---
title: API for test scaffolder!

/books:
  get:
    description: Retrieve a list of all the books
    responses: 
      200:
        body: 
          application/json:
        
/movies:
  patch:
  
/shows:
  put: