#%RAML 1.0 Library
usage: This library contains some data types

uses:
  library: /library.raml

types:
  stuff:
    type: object
    properties: 
      foo: string
      bar: number
    example:
      foo: "hello"
      bar: 42

  moreStuff:
    type: library.ComplexType
    properties:
      foo: string
      bar: boolean
    example:
      name2: test
      length2: 2
      foo: "bye"
      bar: false
