#%RAML 0.8
---
title: RAML Example API
version: v1
baseUri: https://www.example.com/api/
/resources:
    get:
        responses:
            200:
                body:
                    application/json: !!null
    put:
        body:
            application/json:
                schema: |
                  {
                    "type": "number",
                    "$schema": "http://json-schema.org/draft-03/schema",
                    "required" : true
                  }
        responses:
            200:
                body:
                    application/json: !!null
    post:
        responses:
            200:
                headers:
                    location:
                        type: string
                        required: true
                body:
                    application/json: !!null
/multipart:
  post:
    body:
      multipart/form-data:
        formParameters:
          first:
            type: string
            required: true
          second:
            type: string
            default: segundo
          third:
            type: boolean
    responses:
      201: ~

/url-encoded:
  post:
    body:
      application/x-www-form-urlencoded:
        formParameters:
          first:
            type: string
            default: primo
          second:
            type: string
            required: true
          third:
            type: boolean
    responses:
      201: ~