#%RAML 1.0 Library
usage: This library contains some data types

types:
  stuff:
    type: object
    properties: 
      foo: string
      bar: number
    example:
      foo: "hello"
      bar: 42

  moreStuff:
    type: object
    properties:
      foo: string
      bar: boolean
    example:
      foo: "bye"
      bar: false
