#set ($muleVersion = $muleVersion.toUpperCase())
#set ($muleVersion = $muleVersion.replace(".",""))
#set ($max = $muleVersion.indexOf("-"))
#if ($max > -1)
#set ($muleVersion = $muleVersion.substring(0, $max))
#end
#set ($10version = "380")
#set ($Integer = 0)
#set ($zeros = "0")
#set ($repeated = $muleVersion.length() - $10version.length() )
#if ($repeated >0)
#set ($zeros = $zeros.repeat($repeated))
#set ($10version = $10version.concat($zeros))
#end
#set ($repeated = $10version.length() - $muleVersion.length())
#if ($repeated > 0)
#set ($zeros = "0")
#set ($zeros = $zeros.repeat($repeated))
#set ($muleVersion = $muleVersion.concat($zeros))
#end
#set( $H = '#' )
#if( $Integer.parseInt($muleVersion)>= $Integer.parseInt($10version)
$H%RAML 1.0
#else
$H%RAML 0.8
#end
title: Sample API
