description: |
  **Important**: OAuth 1.0 has been officially deprecated as of April 20, 2012. It will continue to work as per our deprecation policy,
  but we encourage you to migrate to OAuth 2.0 as soon as possible.
type: OAuth 1.0
settings: 
  requestTokenUri: https://www.google.com/accounts/OAuthGetRequestToken
  authorizationUri: https://www.google.com/accounts/OAuthAuthorizeToken
  tokenCredentialsUri: https://www.google.com/accounts/OAuthGetAccessToken
