#%RAML 1.0
title: RAML 1.0 Query String
version: v1
baseUri: https://www.example.com/api/

/querystring:
    get:
        queryParameters:
          stringQueryParam:
            type: string
            minLength: 2
            maxLength: 10
            enum: ["enum1", "enum2"]
            default: "enum1"
          numberQueryParam:
            type: number
            minimum: 10.10
            maximum: 20.20
            default: 15.15
          integerQueryParam:
            type: integer
            minimum: 10
            maximum: 20
            default: 15
          dateQueryParam:
            type: datetime
            format: rfc2616
            default: "Sun, 06 Nov 1994 08:49:37 GMT"
          booleanQueryParam:
            type: boolean
            default: false
          fileQueryParam:
            type: file
          queryParamWithoutType:

/querystring/array:
    get:
        queryParameters:
          stringQueryParam:
            type: string[]
            minItems: 3
            maxItems: 10
            default: ["1", "2", "3"]
          numberQueryParam:
            type: number[]
            default: [15.15]
          integerQueryParam:
            type: integer[]
            default: [15]
          dateQueryParam:
            type: datetime[]
            default: ["2016-02-28T16:41:41.090Z"]
          booleanQueryParam:
            type: boolean[]
            default: [false]
          fileQueryParam:
            type: file[]