#%RAML 1.0 DataType

usage: Standard error message

type: object
displayName: Standard Error Message
properties:
  code:
    type: number
    format: int32
  name:
    type: string
  reason:
    type: string
  message:
    type: string
  trace_id:
    type: string
