#%RAML 1.0
title: Headers Test Case

/resource/{param}:
  uriParameters:
    param:
      type: integer
      required: true
  get:

/escaped/{anyvalue}:
  uriParameters:
    anyvalue: string
  get:

/list/{param}:
  uriParameters:
    param:
      type: integer
      required: false
  get:

/uriparam:
  get:
  /{optional}:
    get:
    uriParameters:
      optional:
        required: false
        type: integer

/dateParam:
  get:
  /{dateValue}:
    get:
    uriParameters:
      dateValue:
        type: datetime