#%RAML 1.0
title: RAML 1.0 Headers
version: v1
baseUri: https://www.example.com/api/

/headers:
    get:
      responses:
        200:
          headers:
            stringHeader:
              type: string
              minLength: 2
              maxLength: 10
              enum: ["enum1", "enum2"]
              default: "enum1"
            numberHeader:
              type: number
              minimum: 10.10
              maximum: 20.20
              default: 15.15
            integerHeader:
              type: integer
              minimum: 10
              maximum: 20
              default: 15
            dateHeader:
              type: datetime
              format: rfc2616
              default: "Sun, 06 Nov 1994 08:49:37 GMT"
            booleanHeader:
              type: boolean
              default: false
            fileHeader:
              type: file
            withoutType:
          body:
            application/json:

/without/headers:
    get:
      responses:
        200:
          headers:

/headers/array:
    get:
      responses:
        200:
          headers:
            arrayOfStringHeader:
              type: string[]
            arrayOfNumberHeader:
              type: number[]
            arrayOfIntegerHeader:
              type: integer[]
            arrayOfDateHeader:
              type: datetime[]
            arrayOfBooleanHeader:
              type: boolean[]
            arrayOfFileHeader:
              type: file[]
          body:
            application/json:
